import type { AdapterSdkDefinition } from "./contracts.js";

export const ADAPTER_SDK_CATALOG: AdapterSdkDefinition[] = [
  {
    key: "design-handoff-adapter",
    name: "Design Handoff Adapter",
    category: "design",
    mode: "active",
    description: "Exports a Figma-friendly design handoff package without making design tooling a runtime dependency.",
    runtimeBoundary: "Factory-owned export/import boundary only. Generation must still succeed when no external design adapter is configured.",
    secretsModel: "No secrets required for local export. Future remote adapters must source credentials from environment or deployment config.",
    failureMode: "Export/import warnings remain visible to the operator and do not block spec parsing or generation.",
    configFields: ["package format version", "optional downstream adapter metadata"],
    hookPoints: ["post-parse design export", "design import validation", "post-generation handoff packaging"],
  },
  {
    key: "figma-bridge-adapter",
    name: "Figma Bridge Adapter",
    category: "design",
    mode: "optional",
    description: "Optional adapter boundary for future Figma API or MCP integration.",
    runtimeBoundary: "Adapter-only. No generated app or operator workflow may hard-require Figma availability.",
    secretsModel: "Figma credentials must remain external and operator-controlled.",
    failureMode: "Gracefully degrade to the local design handoff package and surface a non-blocking warning.",
    configFields: ["file id", "team id", "access token reference"],
    hookPoints: ["design export sync", "design import sync"],
  },
  {
    key: "csv-batch-gateway",
    name: "CSV Batch Gateway",
    category: "files",
    mode: "active",
    description: "Supports typed CSV import/export contracts with approval review for multi-record mutations.",
    runtimeBoundary: "Generated apps own batch persistence and execution; the factory only scaffolds the contract and review posture.",
    secretsModel: "No secrets required for local CSV handling.",
    failureMode: "Import stays blocked behind visible validation errors or approval requirements.",
    configFields: ["import schema version", "export fields", "approval gate key"],
    hookPoints: ["generated runtime adapter manifest", "integration panel", "eval coverage"],
  },
  {
    key: "identity-provider-adapter",
    name: "Identity Provider Adapter",
    category: "identity",
    mode: "future-ready",
    description: "Keeps SSO/IdP selection explicit without hard-coding provider assumptions.",
    runtimeBoundary: "Factory records the boundary and generated apps implement the final auth integration.",
    secretsModel: "OIDC/SAML credentials must remain in deployment config only.",
    failureMode: "Stay in deferred status until provider, redirect URIs, and tenant mapping are confirmed.",
    configFields: ["provider family", "tenant claim mapping", "fallback admin bootstrap policy"],
    hookPoints: ["spec compiler", "generated runtime kit", "settings and handoff docs"],
  },
  {
    key: "erp-sync-sdk",
    name: "ERP Sync SDK",
    category: "erp",
    mode: "future-ready",
    description: "Defines a contract-first ERP adapter boundary with explicit approval and persistence ownership.",
    runtimeBoundary: "Generated apps own business writes; the adapter contract only describes how approved syncs should behave.",
    secretsModel: "ERP credentials and webhook secrets must remain external.",
    failureMode: "Deferred until the customer confirms vendor, field mapping, direction, and approval posture.",
    configFields: ["vendor", "sync direction", "field contract", "retry policy"],
    hookPoints: ["integration planning", "generated runtime adapter manifest", "eval coverage"],
  },
  {
    key: "notification-router-adapter",
    name: "Notification Router Adapter",
    category: "notifications",
    mode: "active",
    description: "Maps notification rules to provider-neutral routing without baking secrets into generated code.",
    runtimeBoundary: "Notification sending is owned by the deployed customer app and its environment configuration.",
    secretsModel: "Provider keys stay in the generated app environment, never in the factory repo.",
    failureMode: "Generation keeps working and the generated app shows unresolved destinations until configured.",
    configFields: ["channels", "provider family", "escalation targets"],
    hookPoints: ["notification rule generation", "settings", "handoff docs"],
  },
];

export function getAdapterDefinition(key: string): AdapterSdkDefinition | undefined {
  return ADAPTER_SDK_CATALOG.find((adapter) => adapter.key === key);
}
