import type { DomainPackSummary } from "./contracts.js";

export const DOMAIN_PACK_CATALOG: DomainPackSummary[] = [
  {
    key: "core-operations",
    name: "Core Operations",
    version: "2026-03-28.v2",
    description: "Baseline enterprise operations pack with tenant-safe admin, workflow, approval, reporting, and settings modules.",
    triggerKeywords: ["operations", "internal", "workflow", "approval", "reporting"],
    selectedWhen: "Always selected as the base compiler pack.",
    moduleKeys: ["dashboard", "entity-workbench", "workflow-orchestrator", "approvals", "audit", "roles", "integrations", "notifications", "reports", "settings"],
    roleKeys: ["platform_admin", "operations_manager", "approver", "auditor", "reporting_analyst"],
    entityKeys: ["approval_request"],
    workflowKeys: ["reporting", "approval"],
    integrationKeys: ["identity_provider", "email_notifications"],
    complianceKeys: ["tenant-isolation", "audit-evidence"],
    adapterKeys: ["design-handoff-adapter", "notification-router-adapter", "identity-provider-adapter"],
    notes: [
      "Preserves least privilege and auditability defaults even when the prompt is sparse.",
      "Provides the operator-visible admin/reporting/governance shell for all generated apps.",
    ],
  },
  {
    key: "healthcare-logistics",
    name: "Healthcare Logistics",
    version: "2026-03-28.v2",
    description: "Healthcare logistics pack for equipment movement, service readiness, and regional hospital operations.",
    triggerKeywords: ["medical", "hospital", "healthcare", "delivery", "pickup", "equipment"],
    selectedWhen: "Selected when the prompt references healthcare, medical logistics, or hospital operations.",
    moduleKeys: ["dispatch-board", "inventory-readiness", "service-ticket-console", "account-operations", "task-assignment"],
    roleKeys: ["dispatch_coordinator", "warehouse_lead", "technician", "account_manager"],
    entityKeys: ["shipment_order", "service_ticket", "inventory_item", "account", "task_assignment"],
    workflowKeys: ["dispatch", "inventory", "service_resolution"],
    integrationKeys: ["csv_exchange", "erp_sync"],
    complianceKeys: ["health-operations-traceability", "audit-evidence"],
    adapterKeys: ["csv-batch-gateway", "erp-sync-sdk"],
    notes: [
      "Adds chain-of-custody friendly entities and readiness-state views.",
      "Keeps ERP and design tooling future-ready rather than hard coupled.",
    ],
  },
  {
    key: "warehouse-operations",
    name: "Warehouse Operations",
    version: "2026-03-28.v2",
    description: "Warehouse pack focused on readiness, transfers, and disposition safeguards.",
    triggerKeywords: ["warehouse", "inventory", "cleaning", "readiness", "asset"],
    selectedWhen: "Selected when the prompt references inventory movement, readiness, or warehouse work.",
    moduleKeys: ["inventory-readiness"],
    roleKeys: ["warehouse_lead"],
    entityKeys: ["inventory_item"],
    workflowKeys: ["inventory"],
    integrationKeys: ["csv_exchange"],
    complianceKeys: ["audit-evidence"],
    adapterKeys: ["csv-batch-gateway"],
    notes: [
      "Strengthens readiness and disposition controls for tenant-scoped assets.",
    ],
  },
  {
    key: "field-service",
    name: "Field Service",
    version: "2026-03-28.v2",
    description: "Field service pack for ticketing, technician assignments, and service verification.",
    triggerKeywords: ["service ticket", "technician", "field", "assignment", "dispatch"],
    selectedWhen: "Selected when the prompt references technician work, field execution, or service tickets.",
    moduleKeys: ["dispatch-board", "service-ticket-console", "task-assignment"],
    roleKeys: ["dispatch_coordinator", "technician"],
    entityKeys: ["service_ticket", "task_assignment"],
    workflowKeys: ["dispatch", "service_resolution"],
    integrationKeys: ["email_notifications"],
    complianceKeys: ["audit-evidence"],
    adapterKeys: ["notification-router-adapter"],
    notes: [
      "Keeps operator-visible service resolution and assignment flows aligned.",
    ],
  },
  {
    key: "account-governance",
    name: "Account and Governance",
    version: "2026-03-28.v2",
    description: "Adds account visibility, approval guardrails, and cross-cutting governance views.",
    triggerKeywords: ["account", "customer", "audit", "approval", "role-based"],
    selectedWhen: "Selected when the prompt references customer account views, auditability, or role governance.",
    moduleKeys: ["account-operations", "approvals", "audit", "roles", "reports"],
    roleKeys: ["account_manager", "auditor", "approver"],
    entityKeys: ["account", "approval_request"],
    workflowKeys: ["approval", "reporting"],
    integrationKeys: ["identity_provider"],
    complianceKeys: ["audit-evidence", "tenant-isolation"],
    adapterKeys: ["identity-provider-adapter"],
    notes: [
      "Makes account visibility and governance controls first-class instead of implicit.",
    ],
  },
];

export function getDomainPack(key: string): DomainPackSummary | undefined {
  return DOMAIN_PACK_CATALOG.find((pack) => pack.key === key);
}
