import type { ModuleRegistryEntry } from "./contracts.js";

export const MODULE_REGISTRY: ModuleRegistryEntry[] = [
  {
    key: "dashboard",
    name: "Operations Dashboard",
    description: "Give operators a live view of workload, approvals, risk, and throughput.",
    kind: "dashboard",
    route: "/dashboard",
    primitive: "kpi-ribbon-and-ops-board",
    domainTags: ["core", "operations"],
    defaultRoles: ["platform_admin", "operations_manager", "dispatch_coordinator", "auditor"],
    editableSurfaces: ["page title", "metric definitions", "alert copy"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["approval-needed", "workflow-at-risk"],
    observability: ["job status summary", "approval backlog", "adapter health summary"],
    widgetBlueprints: [
      { key: "stats", title: "Operational Stats", kind: "stat-grid", source: "spec.summary", description: "Summarize entities, workflows, approvals, and integrations." },
      { key: "workflow-highlights", title: "Workflow Highlights", kind: "workflow-list", source: "spec.coreWorkflows", description: "Expose the main workflow lanes and ownership." },
      { key: "report-highlights", title: "Reporting Highlights", kind: "report-list", source: "spec.reportingViews", description: "Surface summary and compliance reports." },
    ],
  },
  {
    key: "entity-workbench",
    name: "Entity Workbench",
    description: "Manage business entities through typed forms, tables, and detail views.",
    kind: "data",
    route: "/entities",
    primitive: "crud-grid-with-detail-rail",
    domainTags: ["core", "data"],
    defaultRoles: ["platform_admin", "operations_manager", "dispatch_coordinator", "warehouse_lead", "technician"],
    editableSurfaces: ["field labels", "empty states", "table density", "filter presets"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["bulk-import"],
    observability: ["entity audit count", "bulk import state"],
    widgetBlueprints: [
      { key: "entity-table", title: "Entity Tables", kind: "entity-table", source: "spec.businessEntities", description: "Show contract-driven entity tables and field sets." },
    ],
  },
  {
    key: "workflow-orchestrator",
    name: "Workflow Orchestrator",
    description: "Track multi-step operational flows with visible ownership and escalation.",
    kind: "workflow",
    route: "/workflows",
    primitive: "timeline-with-stage-actions",
    domainTags: ["core", "workflow"],
    defaultRoles: ["platform_admin", "operations_manager", "dispatch_coordinator", "warehouse_lead", "technician"],
    editableSurfaces: ["stage labels", "escalation copy", "checklist text"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["urgent-replacement", "inventory-disposition"],
    observability: ["workflow stage health", "stale work count"],
    widgetBlueprints: [
      { key: "workflow-list", title: "Workflow Timeline", kind: "workflow-list", source: "spec.coreWorkflows", description: "Show stage-by-stage workflow progress and ownership." },
    ],
  },
  {
    key: "dispatch-board",
    name: "Dispatch Board",
    description: "A dispatch-focused board for delivery, pickup, and field-routing work.",
    kind: "workflow",
    route: "/dispatch",
    primitive: "dispatch-kanban",
    domainTags: ["logistics", "field-service"],
    defaultRoles: ["dispatch_coordinator", "operations_manager", "technician"],
    editableSurfaces: ["dispatch columns", "route copy", "priority badges"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["urgent-replacement"],
    observability: ["dispatch queue", "at-risk windows"],
    widgetBlueprints: [
      { key: "dispatch-flows", title: "Dispatch Flows", kind: "workflow-list", source: "workflow.dispatch", description: "Surface delivery and pickup workflow lanes." },
      { key: "dispatch-orders", title: "Dispatch Orders", kind: "entity-table", source: "entity.shipment_order", description: "List dispatch-ready shipment orders." },
    ],
  },
  {
    key: "service-ticket-console",
    name: "Service Ticket Console",
    description: "Review service request intake, ownership, and field resolution state.",
    kind: "workflow",
    route: "/service-tickets",
    primitive: "ticket-console",
    domainTags: ["field-service", "support"],
    defaultRoles: ["dispatch_coordinator", "technician", "operations_manager"],
    editableSurfaces: ["ticket status labels", "triage prompts", "resolution copy"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["urgent-replacement"],
    observability: ["ticket backlog", "stale resolution count"],
    widgetBlueprints: [
      { key: "service-workflow", title: "Service Resolution", kind: "workflow-list", source: "workflow.service_resolution", description: "Track ticket triage, assignment, and close-out." },
      { key: "service-tickets", title: "Service Tickets", kind: "entity-table", source: "entity.service_ticket", description: "List active service tickets and resolution state." },
    ],
  },
  {
    key: "inventory-readiness",
    name: "Inventory Readiness",
    description: "Show warehouse readiness, cleaning status, and movement events.",
    kind: "data",
    route: "/inventory",
    primitive: "readiness-board",
    domainTags: ["warehouse", "logistics"],
    defaultRoles: ["warehouse_lead", "operations_manager", "technician"],
    editableSurfaces: ["status chips", "readiness copy", "storage views"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["inventory-disposition"],
    observability: ["inventory readiness alerts", "transfer backlog"],
    widgetBlueprints: [
      { key: "inventory-workflow", title: "Inventory Flow", kind: "workflow-list", source: "workflow.inventory", description: "Track receive, ready, transfer, and retire flows." },
      { key: "inventory-table", title: "Inventory Items", kind: "entity-table", source: "entity.inventory_item", description: "Expose inventory readiness and location state." },
    ],
  },
  {
    key: "account-operations",
    name: "Account Operations",
    description: "Account-level visibility for service history, regions, and risk.",
    kind: "data",
    route: "/accounts",
    primitive: "account-summary-board",
    domainTags: ["accounts", "customer-ops"],
    defaultRoles: ["account_manager", "operations_manager", "dispatch_coordinator"],
    editableSurfaces: ["account summary copy", "region groupings", "service-tier labels"],
    requiredAdapterKeys: [],
    approvalTouchpoints: [],
    observability: ["account risk flags", "regional load"],
    widgetBlueprints: [
      { key: "account-table", title: "Accounts", kind: "entity-table", source: "entity.account", description: "Summarize account status and regional footprint." },
      { key: "account-reports", title: "Account Reports", kind: "report-list", source: "spec.reportingViews", description: "Show account-relevant reporting surfaces." },
    ],
  },
  {
    key: "task-assignment",
    name: "Task Assignment Board",
    description: "Track technician and operator assignments with due dates and escalation paths.",
    kind: "workflow",
    route: "/tasks",
    primitive: "assignment-board",
    domainTags: ["field-service", "operations"],
    defaultRoles: ["technician", "dispatch_coordinator", "operations_manager"],
    editableSurfaces: ["task grouping", "assignment copy", "priority thresholds"],
    requiredAdapterKeys: [],
    approvalTouchpoints: [],
    observability: ["assignment backlog", "overdue task count"],
    widgetBlueprints: [
      { key: "task-table", title: "Task Assignments", kind: "entity-table", source: "entity.task_assignment", description: "List assignments, owners, and due dates." },
      { key: "task-flow", title: "Task Workflow", kind: "workflow-list", source: "workflow.service_resolution", description: "Show task-related service flow." },
    ],
  },
  {
    key: "approvals",
    name: "Approval Center",
    description: "Keep irreversible actions behind explicit review and audit events.",
    kind: "approval",
    route: "/approvals",
    primitive: "approval-queue",
    domainTags: ["core", "governance"],
    defaultRoles: ["platform_admin", "operations_manager", "approver", "auditor"],
    editableSurfaces: ["decision prompts", "risk labels", "approval instructions"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["urgent-replacement", "inventory-disposition", "bulk-import", "rbac-change"],
    observability: ["approval backlog", "decision latency"],
    widgetBlueprints: [
      { key: "approval-list", title: "Approval Queue", kind: "approval-list", source: "spec.approvalGates", description: "List active approval gates and risk descriptions." },
    ],
  },
  {
    key: "audit",
    name: "Audit Stream",
    description: "Trace meaningful workflow events and changes across the tenant boundary.",
    kind: "audit",
    route: "/audit",
    primitive: "append-only-event-log",
    domainTags: ["core", "governance"],
    defaultRoles: ["platform_admin", "operations_manager", "auditor"],
    editableSurfaces: ["audit copy", "filter presets", "export labels"],
    requiredAdapterKeys: [],
    approvalTouchpoints: [],
    observability: ["audit feed", "attribution summary"],
    widgetBlueprints: [
      { key: "audit-feed", title: "Audit Feed", kind: "audit-feed", source: "spec.blueprint.observability", description: "Explain the audit and observability posture for generated apps." },
    ],
  },
  {
    key: "roles",
    name: "Roles and Access",
    description: "Review least-privilege access and approval scopes by role.",
    kind: "access",
    route: "/roles",
    primitive: "permissions-matrix",
    domainTags: ["core", "governance"],
    defaultRoles: ["platform_admin", "operations_manager", "auditor"],
    editableSurfaces: ["permission labels", "approval scope notes", "role summaries"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["rbac-change"],
    observability: ["role review coverage"],
    widgetBlueprints: [
      { key: "role-list", title: "Roles", kind: "role-list", source: "spec.userRoles", description: "List roles, modules, and approval scopes." },
    ],
  },
  {
    key: "integrations",
    name: "Integrations",
    description: "Make sync boundaries, credential ownership, and failure modes explicit.",
    kind: "integration",
    route: "/integrations",
    primitive: "integration-registry",
    domainTags: ["core", "integration"],
    defaultRoles: ["platform_admin", "operations_manager"],
    editableSurfaces: ["integration notes", "adapter policy copy", "sync labels"],
    requiredAdapterKeys: ["design-handoff-adapter"],
    approvalTouchpoints: ["bulk-import"],
    observability: ["adapter health", "deferred integration list"],
    widgetBlueprints: [
      { key: "integration-list", title: "Integrations", kind: "integration-list", source: "spec.integrations", description: "List integration boundaries and activation status." },
    ],
  },
  {
    key: "notifications",
    name: "Notifications",
    description: "Configure operator-facing rules and escalation paths.",
    kind: "notification",
    route: "/notifications",
    primitive: "rules-and-routing",
    domainTags: ["core", "operations"],
    defaultRoles: ["platform_admin", "operations_manager"],
    editableSurfaces: ["notification copy", "channel labels", "escalation notes"],
    requiredAdapterKeys: ["notification-router-adapter"],
    approvalTouchpoints: [],
    observability: ["notification rules"],
    widgetBlueprints: [
      { key: "notification-list", title: "Notifications", kind: "notification-list", source: "spec.notificationRules", description: "Show notification rules and escalation behavior." },
    ],
  },
  {
    key: "reports",
    name: "Reports",
    description: "Expose operational summaries and trend views for review.",
    kind: "reporting",
    route: "/reports",
    primitive: "report-catalog",
    domainTags: ["core", "analytics"],
    defaultRoles: ["platform_admin", "operations_manager", "auditor", "reporting_analyst"],
    editableSurfaces: ["report titles", "metric descriptions", "cadence copy"],
    requiredAdapterKeys: [],
    approvalTouchpoints: [],
    observability: ["report freshness"],
    widgetBlueprints: [
      { key: "report-list", title: "Reports", kind: "report-list", source: "spec.reportingViews", description: "Show the report catalog and cadence." },
    ],
  },
  {
    key: "settings",
    name: "Settings",
    description: "Handle tenant-aware configuration without hard-coding secrets or approvals.",
    kind: "settings",
    route: "/settings",
    primitive: "settings-rail",
    domainTags: ["core", "admin"],
    defaultRoles: ["platform_admin", "operations_manager"],
    editableSurfaces: ["settings section copy", "tenant policy notes", "branding controls"],
    requiredAdapterKeys: [],
    approvalTouchpoints: ["rbac-change", "bulk-import"],
    observability: ["settings change review"],
    widgetBlueprints: [
      { key: "settings-list", title: "Settings", kind: "settings-list", source: "spec.settingsSections", description: "Show settings sections and ownership." },
    ],
  },
];

export function getModuleRegistryEntry(key: string): ModuleRegistryEntry | undefined {
  return MODULE_REGISTRY.find((entry) => entry.key === key);
}
