import { startTransition, useDeferredValue, useEffect, useMemo, useState, type ReactElement } from "react";
import type {
  AdapterSdkDefinition,
  AgentDefinition,
  AgentRegistry,
  AgentRun,
  AgentRunNode,
  CompilerReport,
  DesignImportResult,
  DesignHandoffPackage,
  DomainPackSummary,
  EnterpriseAppSpec,
  EvalSuiteResult,
  GenerationArtifact,
  GenerationJob,
  GeneratedRuntimeKit,
  ModuleRegistryEntry,
  OperatorPromptInput,
  ValidationResult,
} from "../shared/contracts.js";

type ParseResponse = {
  prompt: OperatorPromptInput;
  spec: EnterpriseAppSpec;
  compilerReport: CompilerReport;
  validation: ValidationResult;
  runtimeKit: GeneratedRuntimeKit;
  evalSuite: EvalSuiteResult;
  designHandoff: DesignHandoffPackage;
  moduleRegistry: ModuleRegistryEntry[];
  selectedDomainPacks: DomainPackSummary[];
  domainPackCatalog: DomainPackSummary[];
  adapterCatalog: AdapterSdkDefinition[];
};

const TAB_ORDER = ["overview", "compiler", "model", "design", "council", "jobs"] as const;
const EMPTY_PROMPT: OperatorPromptInput = { customerName: "", businessDescription: "", applicationNeeds: "", constraints: { industry: "", compliance: [], integrations: [], branding: {}, roles: [], approvalRequirements: [], environment: "", deploymentTarget: "", tenancy: "multi-tenant" } };

async function getJson<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T>; }
async function postJson<T>(url: string, body: unknown): Promise<T> { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T>; }
function listToText(items: string[]): string { return items.join(", "); }
function textToList(value: string): string[] { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function supportClass(value: string): string { return value === "supported" || value === "passed" || value === "completed" ? "status-good" : value === "warning" || value === "planned" ? "status-caution" : value === "unsupported" || value === "failed" ? "status-risk" : "status-muted"; }
function artifactDownloadUrl(job: GenerationJob, artifact: GenerationArtifact): string { return `/api/factory/jobs/${job.id}/artifacts/${artifact.key}/download`; }
function sortSeatOptions(registry: AgentRegistry | null): AgentDefinition[] { return registry?.agents.filter((agent) => agent.type === "council-seat") ?? []; }

function AgentTree({ node }: { node: AgentRunNode }): ReactElement {
  return <article className={`agent-node depth-${Math.min(node.depth, 3)}`}><header className="agent-node-header"><div><p className="eyebrow">{node.type}</p><h4>{node.name}</h4><p>{node.summary}</p></div><span className={`job-status ${node.status}`}>{node.status}</span></header>{node.findings.length > 0 ? <ul className="line-list compact">{node.findings.map((item) => <li key={`${node.id}-${item.title}`}><strong>{item.severity.toUpperCase()}</strong> {item.title}: {item.detail}</li>)}</ul> : null}{node.children.length > 0 ? <div className="agent-children">{node.children.map((child) => <AgentTree key={child.id} node={child} />)}</div> : null}</article>;
}

function CapabilityMatrix({ registry }: { registry: AgentRegistry | null }): ReactElement {
  return <div className="capability-grid">{registry?.capabilityMatrix.map((capability) => <article key={capability.key} className="capability-card"><div className="capability-head"><h4>{capability.label}</h4><span className={supportClass(capability.support)}>{capability.support}</span></div><p>{capability.notes}</p></article>) ?? <p>No capability registry loaded yet.</p>}</div>;
}

export default function App(): ReactElement {
  const [prompt, setPrompt] = useState<OperatorPromptInput>(EMPTY_PROMPT);
  const [parseResult, setParseResult] = useState<ParseResponse | null>(null);
  const [jobs, setJobs] = useState<GenerationJob[]>([]);
  const [currentJob, setCurrentJob] = useState<GenerationJob | null>(null);
  const [agentRegistry, setAgentRegistry] = useState<AgentRegistry | null>(null);
  const [agentRuns, setAgentRuns] = useState<AgentRun[]>([]);
  const [currentAgentRun, setCurrentAgentRun] = useState<AgentRun | null>(null);
  const [moduleRegistry, setModuleRegistry] = useState<ModuleRegistryEntry[]>([]);
  const [domainPackCatalog, setDomainPackCatalog] = useState<DomainPackSummary[]>([]);
  const [adapterCatalog, setAdapterCatalog] = useState<AdapterSdkDefinition[]>([]);
  const [activeTab, setActiveTab] = useState<(typeof TAB_ORDER)[number]>("overview");
  const [operatorName, setOperatorName] = useState("Enterprise Operator");
  const [approvalReason, setApprovalReason] = useState("Generate an editable customer workspace from the reviewed compiler output.");
  const [designImportText, setDesignImportText] = useState("");
  const [designImportResult, setDesignImportResult] = useState<DesignImportResult | null>(null);
  const [jobFilter, setJobFilter] = useState("");
  const [agentFocusText, setAgentFocusText] = useState("architecture, security, download, test");
  const [requestedSeatKeys, setRequestedSeatKeys] = useState<string[]>([]);
  const [allowDelegation, setAllowDelegation] = useState(true);
  const [delegationDepth, setDelegationDepth] = useState(3);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const deferredJobFilter = useDeferredValue(jobFilter);

  useEffect(() => { void (async () => { try { const [defaultPrompt, initialJobs, registry, initialAgentRuns, initialModules, initialPacks, initialAdapters] = await Promise.all([getJson<OperatorPromptInput>("/api/factory/default-prompt"), getJson<GenerationJob[]>("/api/factory/jobs"), getJson<AgentRegistry>("/api/factory/agent-registry"), getJson<AgentRun[]>("/api/factory/agent-runs"), getJson<ModuleRegistryEntry[]>("/api/factory/module-registry"), getJson<DomainPackSummary[]>("/api/factory/domain-packs"), getJson<AdapterSdkDefinition[]>("/api/factory/adapters")]); startTransition(() => { setPrompt(defaultPrompt); setJobs(initialJobs); setCurrentJob(initialJobs[0] ?? null); setAgentRegistry(registry); setAgentRuns(initialAgentRuns); setCurrentAgentRun(initialAgentRuns[0] ?? null); setModuleRegistry(initialModules); setDomainPackCatalog(initialPacks); setAdapterCatalog(initialAdapters); }); } catch (loadError) { setError((loadError as Error).message); } })(); }, []);
  useEffect(() => { if (!currentJob || !["queued", "running"].includes(currentJob.status)) return; const handle = window.setInterval(() => { void (async () => { try { const job = await getJson<GenerationJob>(`/api/factory/jobs/${currentJob.id}`); startTransition(() => { setCurrentJob(job); setJobs((previous) => [job, ...previous.filter((candidate) => candidate.id !== job.id)]); }); } catch (pollError) { setError((pollError as Error).message); } })(); }, 2000); return () => window.clearInterval(handle); }, [currentJob]);

  const visibleJobs = useMemo(() => { const query = deferredJobFilter.trim().toLowerCase(); return !query ? jobs : jobs.filter((job) => [job.spec.customerProfile.name, job.status, job.approval.approvedBy].join(" ").toLowerCase().includes(query)); }, [deferredJobFilter, jobs]);
  const displaySpec = parseResult?.spec ?? currentJob?.spec ?? currentAgentRun?.request.spec ?? null;
  const displayValidation = parseResult?.validation ?? currentJob?.validation ?? null;
  const displayCompiler = parseResult?.compilerReport ?? currentJob?.compilerReport ?? displaySpec?.compiler ?? null;
  const displayRuntimeKit = parseResult?.runtimeKit ?? currentJob?.runtimeKit ?? null;
  const displayEvalSuite = parseResult?.evalSuite ?? currentJob?.evalSuite ?? null;
  const displayDesign = parseResult?.designHandoff ?? null;
  const selectedPacks = parseResult?.selectedDomainPacks ?? (displayCompiler ? domainPackCatalog.filter((pack) => displayCompiler.selectedDomainPackKeys.includes(pack.key)) : []);
  const seatOptions = sortSeatOptions(agentRegistry);
  const metricCards = displaySpec ? [{ label: "Entities", value: String(displaySpec.businessEntities.length) }, { label: "Workflows", value: String(displaySpec.coreWorkflows.length) }, { label: "Modules", value: String(displayRuntimeKit?.pages.length ?? displaySpec.moduleSelections.length) }, { label: "Adapters", value: String(displaySpec.adapterBindings.length) }, { label: "Eval", value: displayEvalSuite ? String(displayEvalSuite.score) : "--" }] : [{ label: "Entities", value: "0" }, { label: "Workflows", value: "0" }, { label: "Modules", value: "0" }, { label: "Adapters", value: "0" }, { label: "Eval", value: "0" }];

  async function handleParse(): Promise<void> { setLoading(true); setError(null); try { const result = await postJson<ParseResponse>("/api/factory/parse", prompt); startTransition(() => { setParseResult(result); setModuleRegistry(result.moduleRegistry); setDomainPackCatalog(result.domainPackCatalog); setAdapterCatalog(result.adapterCatalog); setActiveTab("overview"); }); } catch (parseError) { setError((parseError as Error).message); } finally { setLoading(false); } }
  async function handleCouncilReview(): Promise<void> { if (!parseResult) return; setLoading(true); setError(null); try { const run = await postJson<AgentRun>("/api/factory/agent-runs", { prompt, spec: parseResult.spec, operator: operatorName, focus: textToList(agentFocusText), requestedSeatKeys, allowDelegation, maxDelegationDepth: delegationDepth, providerMode: "deterministic" }); startTransition(() => { setCurrentAgentRun(run); setAgentRuns((previous) => [run, ...previous.filter((candidate) => candidate.id !== run.id)]); setActiveTab("council"); }); } catch (runError) { setError((runError as Error).message); } finally { setLoading(false); } }
  async function handleGenerate(): Promise<void> { if (!parseResult) return; setLoading(true); setError(null); try { const job = await postJson<GenerationJob>("/api/factory/generate", { prompt, spec: parseResult.spec, approval: { approvedBy: operatorName, approvedAt: new Date().toISOString(), reason: approvalReason, acknowledgedRisks: ["Workspace files will be written to generated-apps", "Verification commands will install dependencies when needed", "Open questions remain visible in the spec, runtime kit, and handoff package"] } }); startTransition(() => { setCurrentJob(job); setJobs((previous) => [job, ...previous.filter((candidate) => candidate.id !== job.id)]); setActiveTab("jobs"); }); } catch (generationError) { setError((generationError as Error).message); } finally { setLoading(false); } }
  async function handleDesignImport(): Promise<void> { setLoading(true); setError(null); try { const result = await postJson<DesignImportResult>("/api/factory/design/import", { packageName: "manual-import", json: designImportText }); startTransition(() => setDesignImportResult(result)); } catch (designError) { setError((designError as Error).message); } finally { setLoading(false); } }
  function toggleSeat(seatKey: string): void { setRequestedSeatKeys((previous) => previous.includes(seatKey) ? previous.filter((candidate) => candidate !== seatKey) : [...previous, seatKey]); }

  return <div className="shell">
    <aside className="rail">
      <div className="brand"><p className="eyebrow">AutoMindLab</p><h1>Enterprise App Factory</h1><p className="lede">Versioned compiler, reusable domain packs, adapter SDK boundaries, evals, and verified runtime-kit generation.</p></div>
      <section className="panel"><h2>Prompt Intake</h2><label>Customer Name<input value={prompt.customerName} onChange={(event) => setPrompt({ ...prompt, customerName: event.target.value })} /></label><label>Business Description<textarea value={prompt.businessDescription} onChange={(event) => setPrompt({ ...prompt, businessDescription: event.target.value })} rows={4} /></label><label>Application Needs<textarea value={prompt.applicationNeeds} onChange={(event) => setPrompt({ ...prompt, applicationNeeds: event.target.value })} rows={6} /></label><label>Industry<input value={prompt.constraints.industry ?? ""} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, industry: event.target.value } })} /></label><label>Compliance<input value={listToText(prompt.constraints.compliance)} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, compliance: textToList(event.target.value) } })} /></label><label>Integrations<input value={listToText(prompt.constraints.integrations)} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, integrations: textToList(event.target.value) } })} /></label><label>Roles<input value={listToText(prompt.constraints.roles)} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, roles: textToList(event.target.value) } })} /></label><label>Approval Requirements<input value={listToText(prompt.constraints.approvalRequirements)} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, approvalRequirements: textToList(event.target.value) } })} /></label><label>Environment<input value={prompt.constraints.environment ?? ""} onChange={(event) => setPrompt({ ...prompt, constraints: { ...prompt.constraints, environment: event.target.value } })} /></label><button className="primary" onClick={() => void handleParse()} disabled={loading}>{loading ? "Working..." : "Compile Spec"}</button></section>
      <section className="panel"><h2>Council Review</h2><p className="panel-copy">Deterministic, operator-visible, and bounded.</p><label>Review Focus<input value={agentFocusText} onChange={(event) => setAgentFocusText(event.target.value)} /></label><div className="seat-picker">{seatOptions.map((seat) => <button key={seat.key} className={requestedSeatKeys.includes(seat.key) ? "seat-chip active" : "seat-chip"} onClick={() => toggleSeat(seat.key)} type="button">{seat.name}</button>)}</div><label className="checkbox"><input type="checkbox" checked={allowDelegation} onChange={(event) => setAllowDelegation(event.target.checked)} />Allow nested delegation</label><label>Max Delegation Depth<input type="number" min={1} max={3} value={delegationDepth} onChange={(event) => setDelegationDepth(Number(event.target.value))} /></label><button className="secondary" onClick={() => void handleCouncilReview()} disabled={!parseResult || loading}>Run Council Review</button></section>
      <section className="panel"><h2>Registry Snapshot</h2><ul className="line-list compact"><li><strong>Modules</strong> {moduleRegistry.length}</li><li><strong>Domain Packs</strong> {domainPackCatalog.length}</li><li><strong>Adapters</strong> {adapterCatalog.length}</li></ul></section>
    </aside>

    <main className="workspace">
      <header className="workspace-header">
        <div className="workspace-hero panel hero-panel"><div><p className="eyebrow">Compiler Review</p><h2>{displaySpec?.customerProfile.name ?? "Awaiting compiled spec"}</h2><p>{displaySpec?.summary ?? "Compile the prompt to review packs, modules, adapters, evals, and generation readiness."}</p></div><div className="metrics-row">{metricCards.map((item) => <div key={item.label} className="metric-card"><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></div>
        <div className="approval-box"><label>Approved By<input value={operatorName} onChange={(event) => setOperatorName(event.target.value)} /></label><label>Approval Reason<textarea value={approvalReason} onChange={(event) => setApprovalReason(event.target.value)} rows={3} /></label><button className="primary" onClick={() => void handleGenerate()} disabled={!parseResult || loading || Boolean(displayValidation && !displayValidation.valid)}>Approve and Generate Package</button></div>
      </header>
      {error ? <div className="error-banner">{error}</div> : null}
      <nav className="tab-strip">{TAB_ORDER.map((tab) => <button key={tab} className={activeTab === tab ? "tab active" : "tab"} onClick={() => setActiveTab(tab)}>{tab}</button>)}</nav>

      {activeTab === "overview" ? <section className="content-grid"><article className="panel"><h3>Validation and Uncertainty</h3><p className={displayValidation?.valid ? "status-good" : "status-risk"}>{displayValidation?.summary ?? "No validation yet."}</p><ul className="line-list">{displayValidation?.issues.length ? displayValidation.issues.map((issue) => <li key={`${issue.code}-${issue.path}`}><strong>{issue.severity.toUpperCase()}</strong> {issue.message}</li>) : <li>Compile the prompt to surface required-field and conflict checks.</li>}</ul>{displaySpec ? <div className="uncertainty-box"><strong>Confidence: {displaySpec.uncertainty.level}</strong><p>{displaySpec.uncertainty.reasons.join(" ")}</p></div> : null}</article><article className="panel"><h3>Eval Summary</h3><p className={supportClass(displayEvalSuite?.overallStatus ?? "warning")}>{displayEvalSuite?.summary ?? "No eval suite yet."}</p><ul className="line-list compact">{displayEvalSuite?.cases.map((entry) => <li key={entry.key}><strong>{entry.label}</strong> {entry.status} / {entry.summary}</li>) ?? <li>Compile the prompt to run compiler evals.</li>}</ul></article><article className="panel"><h3>Assumptions and Unresolved Items</h3><div className="split-list"><div><h4>Assumptions</h4><ul className="line-list">{displaySpec?.assumptions.map((item) => <li key={item}>{item}</li>) ?? <li>No assumptions yet.</li>}</ul></div><div><h4>Unresolved</h4><ul className="line-list">{displaySpec?.unresolvedItems.map((item) => <li key={item}>{item}</li>) ?? <li>No unresolved items yet.</li>}</ul></div></div></article><article className="panel full"><h3>Generated Runtime Preview</h3><div className="entity-grid">{displayRuntimeKit?.pages.map((page) => <article key={page.key} className="entity"><h4>{page.title}</h4><p>{page.summary}</p><p className="meta">{page.route}</p><ul className="line-list compact">{page.widgets.map((widget) => <li key={widget.key}>{widget.title} ({widget.kind})</li>)}</ul></article>) ?? <p>Compile the prompt to preview the runtime kit.</p>}</div></article></section> : null}

      {activeTab === "compiler" ? <section className="content-grid"><article className="panel"><h3>Compiler Stages</h3><div className="stage-stack">{displayCompiler?.stageResults.map((stage) => <article key={stage.key} className="stage-card"><div className="stage-head"><div><p className="eyebrow">{stage.key}</p><h4>{stage.name}</h4></div><span className={supportClass(stage.status)}>{stage.status}</span></div><p>{stage.summary}</p>{stage.selectedKeys.length > 0 ? <p className="meta">Selected: {stage.selectedKeys.join(", ")}</p> : null}{stage.warnings.length > 0 ? <ul className="line-list compact">{stage.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : null}</article>) ?? <p>Compile the prompt to inspect compiler stages.</p>}</div></article><article className="panel"><h3>Selected Domain Packs</h3><div className="entity-grid">{selectedPacks.map((pack) => <article key={pack.key} className="entity"><h4>{pack.name}</h4><p>{pack.description}</p><p className="meta">{pack.key}</p><small>Modules: {pack.moduleKeys.join(", ")}</small></article>)}</div></article><article className="panel"><h3>Module Selections</h3><div className="entity-grid">{displaySpec?.moduleSelections.map((item) => <article key={item.key} className="entity"><h4>{item.name}</h4><p>{item.reason}</p><p className="meta">{item.route}</p><small>{item.kind} / {item.source}</small></article>) ?? <p>No module selections yet.</p>}</div></article><article className="panel"><h3>Adapter Bindings</h3><div className="entity-grid">{displaySpec?.adapterBindings.map((binding) => <article key={binding.key} className="entity"><div className="capability-head"><h4>{binding.name}</h4><span className={supportClass(binding.status)}>{binding.status}</span></div><p>{binding.reason}</p><ul className="line-list compact">{binding.reviewNotes.map((note) => <li key={note}>{note}</li>)}</ul></article>) ?? <p>No adapter bindings yet.</p>}</div></article><article className="panel full"><h3>Registry Catalogs</h3><div className="split-list"><div><h4>Module Registry</h4><ul className="line-list compact">{moduleRegistry.map((entry) => <li key={entry.key}><strong>{entry.name}</strong> {entry.route}</li>)}</ul></div><div><h4>Adapter SDK</h4><ul className="line-list compact">{adapterCatalog.map((adapter) => <li key={adapter.key}><strong>{adapter.name}</strong> {adapter.mode}</li>)}</ul></div></div></article></section> : null}

      {activeTab === "model" ? <section className="content-grid"><article className="panel"><h3>Entity Model</h3><div className="entity-grid">{displaySpec?.businessEntities.map((entity) => <article key={entity.key} className="entity"><h4>{entity.label}</h4><p>{entity.description}</p><p className="meta">{entity.operations.join(" / ")}</p><ul className="line-list compact">{entity.fields.map((field) => <li key={field.key}>{field.label} ({field.type})</li>)}</ul></article>) ?? <p>Compile the prompt to derive entities.</p>}</div></article><article className="panel"><h3>Workflows</h3>{displaySpec?.coreWorkflows.map((workflow) => <article key={workflow.key} className="workflow"><header><h4>{workflow.name}</h4><p>{workflow.description}</p></header><ol className="timeline">{workflow.steps.map((step) => <li key={step.key}><strong>{step.label}</strong><span>{step.action}</span><small>{step.ownerRoles.join(", ")}</small></li>)}</ol></article>) ?? <p>Compile the prompt to derive workflows.</p>}</article><article className="panel"><h3>Roles and Permissions</h3><ul className="line-list">{displaySpec?.userRoles.map((role) => <li key={role.key}><strong>{role.name}</strong> {role.description}</li>) ?? <li>No roles yet.</li>}</ul></article><article className="panel"><h3>Integrations and Compliance</h3><ul className="line-list">{displaySpec?.integrations.map((integration) => <li key={integration.key}><strong>{integration.name}</strong> {integration.notes}</li>) ?? <li>No integrations yet.</li>}</ul><div className="divider" /><ul className="line-list">{displaySpec?.complianceRequirements.map((requirement) => <li key={requirement.key}><strong>{requirement.name}</strong> {requirement.controls.join(", ")}</li>) ?? <li>No compliance requirements yet.</li>}</ul></article></section> : null}

      {activeTab === "design" ? <section className="content-grid"><article className="panel"><h3>Design Export</h3><p className="panel-copy">The design handoff stays optional and adapter-based. Generation never depends on external design tooling.</p>{displayDesign ? <><ul className="line-list compact"><li><strong>Tokens</strong> {displayDesign.tokens.length}</li><li><strong>Token Collections</strong> {displayDesign.tokenCollections.length}</li><li><strong>Screens</strong> {displayDesign.screenMap.length}</li><li><strong>Sections</strong> {displayDesign.pageSections.length}</li><li><strong>Content Model Entries</strong> {displayDesign.contentModel.length}</li></ul><pre>{JSON.stringify(displayDesign, null, 2)}</pre></> : <pre>Compile the prompt to prepare design export output.</pre>}</article><article className="panel"><h3>Design Import</h3><textarea value={designImportText} onChange={(event) => setDesignImportText(event.target.value)} rows={18} /><button className="secondary" onClick={() => void handleDesignImport()} disabled={loading || !designImportText.trim()}>Validate Imported Package</button>{designImportResult ? <pre>{JSON.stringify(designImportResult, null, 2)}</pre> : null}</article></section> : null}

      {activeTab === "council" ? <section className="content-grid"><article className="panel"><h3>Council Registry</h3><div className="entity-grid">{seatOptions.map((seat) => <article key={seat.key} className="entity"><h4>{seat.name}</h4><p>{seat.description}</p><p className="meta">{seat.lens}</p><small>Delegates: {seat.allowedDelegates.join(", ")}</small></article>)}</div><div className="divider" /><CapabilityMatrix registry={agentRegistry} /></article><article className="panel"><h3>Latest Council Run</h3><p className="panel-copy">Recent runs recorded: {agentRuns.length}</p>{currentAgentRun ? <><p><strong>Provider:</strong> {currentAgentRun.providerMode}</p><p>{currentAgentRun.summary}</p><ul className="line-list compact">{currentAgentRun.delegationPlan.map((entry, index) => <li key={`${entry.from}-${entry.to}-${index}`}><strong>{entry.from}</strong> {"->"} <strong>{entry.to}</strong>: {entry.purpose}</li>)}</ul>{currentAgentRun.warnings.length > 0 ? <div className="uncertainty-box"><strong>Warnings</strong><p>{currentAgentRun.warnings.join(" ")}</p></div> : null}<AgentTree node={currentAgentRun.root} /></> : <p>Run a council review after compiling a prompt to inspect bounded seat delegation and capability coverage.</p>}</article></section> : null}

      {activeTab === "jobs" ? <section className="content-grid"><article className="panel"><h3>Generation Jobs</h3><label>Filter Jobs<input value={jobFilter} onChange={(event) => setJobFilter(event.target.value)} /></label><ul className="line-list">{visibleJobs.map((job) => <li key={job.id}><button className="job-link" onClick={() => setCurrentJob(job)}>{job.spec.customerProfile.name}</button><span className={`job-status ${job.status}`}>{job.status}</span></li>)}</ul></article><article className="panel"><h3>Selected Job</h3>{currentJob ? <><p><strong>{currentJob.spec.customerProfile.name}</strong></p><p>{currentJob.workspacePath ?? "Workspace pending."}</p><ul className="line-list compact">{currentJob.verification.map((step) => <li key={step.step}><strong>{step.step}</strong> {step.status}</li>)}</ul><div className="divider" /><h4>Downloads</h4><ul className="line-list compact">{currentJob.artifacts.filter((artifact) => artifact.downloadable).map((artifact) => <li key={artifact.key}><a href={artifactDownloadUrl(currentJob, artifact)}>{artifact.label}</a></li>)}</ul><div className="divider" /><h4>Runtime Kit and Evals</h4><ul className="line-list compact"><li><strong>Compiler</strong> {currentJob.compilerReport.compilerVersion}</li><li><strong>Runtime Kit</strong> {currentJob.runtimeKit.kitVersion}</li><li><strong>Eval Score</strong> {currentJob.evalSuite.score}</li></ul>{currentJob.handoff ? <><div className="divider" /><h4>Ready-To-Test Handoff</h4><ul className="line-list compact">{currentJob.handoff.startupInstructions.map((item) => <li key={item}>{item}</li>)}</ul><div className="split-list"><div><h4>Next Edits</h4><ul className="line-list compact">{currentJob.handoff.nextRecommendedEdits.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>Runtime Highlights</h4><ul className="line-list compact">{currentJob.handoff.runtimeKitHighlights.map((item) => <li key={item}>{item}</li>)}</ul></div></div></> : null}<div className="divider" /><pre>{JSON.stringify(currentJob.logs, null, 2)}</pre></> : <p>No job selected yet.</p>}</article></section> : null}
    </main>
  </div>;
}
